### ISSUE TITLE
contentBaseUrl not working with hash sign.

### ISSUE THREAD

**Issue by nietsmmar** [Floating-Dartists/matomo-tracker#132] opened 2024-01-11 16:12 UTC
**Describe the bug**
I am initializing my MatomoTracker with:

```
await MatomoTracker.instance.initialize(
    siteId: ID,
    url: 'URL,
    cookieless: true,
    contentBaseUrl: 'https://www.example.com/#/',
  );
```

And triggering like this: 

```
const TraceableWidget(
        actionName: 'test',
        path: 'test',
        child: TestPage(),
      ),
```
      
but when doing this, I get this as a result in Matomo:

![image](https://github.com/Floating-Dartists/matomo-tracker/assets/9265181/86421cd7-c015-4d68-baf2-b0e9fe7cbe2a)

It only shows the first part of the baseUrl without the hash sign and without the path attribute from the site where it got triggered. 

The same happens, when adding the `#/` to the path and removing it from the baseUrl.

**To Reproduce**
1. Set a baseUrl ending with `/#/`
2. Trigger any TraceableWidget

**Expected behavior**
I expect the shown URL to be `https://www.example.com/#/test`

**Desktop (please complete the following information):**
 - OS: manjaro
 - Browser chrome,

**Comment by TesteurManiak** [comment] 2024-01-11 16:35
Hi @nietsmmar, you can check the content of the event send to Matomo with the debug logs. Were you able to assert that the event sent contained the correct `url` property or not?

**Comment by nietsmmar** [comment] 2024-01-11 16:38
@TesteurManiak Where are the debug logs located? I am having trouble finding them.

**Comment by TesteurManiak** [comment] 2024-01-11 16:45
> @TesteurManiak Where are the debug logs located? I am having trouble finding them.

It will depend on the IDE you're using. For VSCode it should be displayed in the "DEBUG CONSOLE" tab.

<img width="550" alt="Capture d'écran 2024-01-11 174217" src="https://github.com/Floating-Dartists/matomo-tracker/assets/14369698/c3f8569d-876e-4748-bd89-59dcb8ee080f">

You'll also have to enable logs when initializing the package:
```dart
MatomoTracker.instance.initialize(
  // ...
  verbosityLevel: Level.all,
);
```

**Comment by nietsmmar** [comment] 2024-01-11 16:52
@TesteurManiak Ahh I thought you mean debug logs in matomo itself. 

I activated debug levels and on initializiation the baseUrl is still correct.
When the event is triggered, this is part of the request params:

`&url=https%3A%2F%2Fapp.articlett.schule%2F%3F%23%2F%2Fsherlock`

it should be: `https://app.articlett.schule/#/sherlock`

But when decoding by myself it looks like this `https://app.articlett.schule/?#//sherlock`

**Comment by TesteurManiak** [comment] 2024-01-11 17:23
Thank you for those details, there might be an encoding step missing for this param. I'm going to investigate it.

**Comment by TesteurManiak** [comment] 2024-01-11 18:26
I've been able to confirm with a unit test that this case is reproducible. But it seems to be because of a bad parsing coming from `Uri.parse`. I'll keep investigating to try to find a workaround to this.

**Comment by TesteurManiak** [comment] 2024-01-12 10:26
The fix was merged, I'll try to release it as a dev version on pub.dev, for now you can make your dependency point directly to the main branch or the latest commit with those changes.

**Comment by nietsmmar** [comment] 2024-01-15 10:13
@TesteurManiak Thanks for the merge. I tested by doing a dependency override. But it does not work for me. I tried to get the debug logs but in this version the String is not complete. It looks like this:

`{requests: [?idsite=4&rec=1&ping=1&action_name…S&pv_id=EKMvW8&cdt=2024-01-15T10%3A02%3A12.638Z]}`

It is somehow contracted with `...`

But behavior is the same as before.

I used this code:
```
dependency_overrides:
  matomo_tracker:
    git:
      url: https://github.com/Floating-Dartists/matomo-tracker.git
      ref: b9d5c3e50b23a0acc33ff5de07540994d8c068da
```

**Comment by TesteurManiak** [comment] 2024-01-15 13:21
@nietsmmar I will need a minimal reproducible example or a unit test then. Currently without a more specific case I'm not able to reproduce this behavior.

**Comment by nietsmmar** [comment] 2024-01-15 13:47
@TesteurManiak I am doing the exact same thing as before. I can try building a minimal example, but this will take some time to do. Do you know how I can get the full logging output? Maybe this would help already.

**Comment by TesteurManiak** [comment] 2024-01-15 14:01
I don't understand why the message is truncated 😅 
You should already have the full output because the default `Logger` class is using the [`log`](https://api.flutter.dev/flutter/dart-developer/log.html) method, the truncated `...` would be displayed because of `print` or if you are inspecting a variable directly through the Dart debugger, but `log` should display the entire message.
If you want to display the logs differently you can still add a listener on the `MatomoTracker.instance.log.onRecord` and print the message with whichever method you'd like.

**Comment by TesteurManiak** [comment] 2024-01-15 14:34
Yeah I think it might be because your URL shouldn't have a `/#/` in its path in the first place, as said in the [PR linked to this issue](https://github.com/Floating-Dartists/matomo-tracker/pull/133#issue-2077392699), [`Uri.parse`](https://api.dart.dev/stable/3.2.4/dart-core/Uri/parse.html) is considering `#` as being the fragment of the URL and I wouldn't be surprised if this kind of parsing would be similar on Matomo's side when decoding the request.
I'll close this issue because it might have something to do in the first place with the URL you're trying to use and there's not much more we can do if the request to Matomo is encoded properly 🤔

**Closed by TesteurManiak** 2024-01-15 14:34 UTC
Labels: bug, needs verification, priority-high

**Comment by nietsmmar** [comment] 2024-01-15 14:51
@TesteurManiak I see. That is problematic. Then I might have to try to change this pathing behavior. In flutter it seems to be default for web. Thanks for your help.

**Comment by c-seeger** [comment] 2024-04-08 13:24
Found a solution by myself. Just adding this in case someone runs into the same issue.

Matomo backend has a setting for this. Going in Settings -> Websites -> select your website and edit it. There is an option `Keep Page URL fragments when tracking Page URLs`, set this to yes and it works.
